version: 0.2

phases:
  pre_build:
    commands:
      - echo Login into ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 028282433975.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=028282433975.dkr.ecr.ap-south-1.amazonaws.com/aws-ecs-ecr-demo
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on date
      - echo Building the jar file
      - mvn clean install
      - echo building the Docker Image 
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing image to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - DOCKER_CONTAINER_NAME= spring-ecr-container-file
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo priting imagedefition.json
      - cat imagedefinitions.json
artifacts:
  files:
    - target/photo-albums-0.0.1-SNAPSHOT.jar
    - imagedefinitions.json